name: juju-db
version: '4.0.9'
summary: Mongodb object/document oriented database used internally by Juju.
description: |
  Mongodb object/document oriented database used internally by Juju.
confinement: strict
grade: devel
base: core18 

apps:
  daemon:
    command: commands/daemon.start
    stop-timeout: 600s
    restart-condition: on-failure
    daemon: simple
    plugs:
      - network-bind

  mongod:
    command: mongod
    plugs:
      - network
      
  mongos:
    command: mongos
    plugs:
      - network

  mongo:
    command: mongo
    plugs:
      - network

  # Tools
  mongodump:
    command: mongodump
    plugs:
      - network

  mongorestore:
    command: mongorestore
    plugs:
      - network

  mongostat:
    command: mongostat
    plugs:
      - network

  mongotop:
    command: mongotop
    plugs:
      - network

parts:
  wrappers:
    plugin: dump
    source: snap/local/

  mongo-tools:
    source: https://github.com/mongodb/mongo-tools
    source-type: git
    source-tag: "r4.0.9"
    plugin: go
    build-packages:
      - gcc
      - pkg-config
      - libssl-dev
      - libpcap0.8-dev
      - libsasl2-dev
    stage-packages:
      - libssl1.1
      - libpcap0.8
      - libsasl2-2
    go-channel: 1.11/stable
    go-importpath: github.com/mongodb/mongo-tools
    override-build: |
      mongo_tools="mongodump mongorestore mongotop mongostat"
      export GOPATH=$(realpath ../go)
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/bin/
      # TODO: maybe set ldflags as per the build script.
      for tool in ${mongo_tools}; do
          go build -v -tags="ssl sasl" -o $GOPATH/bin/$tool github.com/mongodb/mongo-tools/$tool/main
          mv $GOPATH/bin/$tool ${SNAPCRAFT_PART_INSTALL}/bin/
      done

  mongo:
    source: https://github.com/mongodb/mongo
    source-type: git
    source-tag: "r4.0.9"
    plugin: scons
    stage-packages:
      - libssl1.1
      - libcurl4
      - libstemmer0d
      - zlib1g
      - libsnappy1v5
      - libyaml-cpp0.5v5
      - libpcre3
      - libpcrecpp0v5
      - libboost-system1.65.1
      - libboost-iostreams1.65.1
      - libboost-filesystem1.65.1
      - libboost-program-options1.65.1
      - libgoogle-perftools4
    build-packages:
      # isn't available on s390x, only needed on the rest anyway.
      - try:
          - libgoogle-perftools-dev
      - libssl-dev
      - libcurl4-openssl-dev
      # python packages cribbed from deb, might need changed.
      - python-cheetah
      - python-pkg-resources
      - python-pymongo
      - python-typing
      - python-yaml
      # I think these and some of the above will be needed as staging packages too (for when its installed and being run).
      # - python-requests
      # - python-subprocess32
      # Package from deb, note scons arg above.
      - libstemmer-dev
      - zlib1g-dev
      - libsnappy-dev
      - libyaml-cpp-dev
      - libpcre3-dev
      - libboost-iostreams-dev
      # packages from the mongodb wiki/doc
      - build-essential
      - libboost-filesystem-dev
      - libboost-program-options-dev
      - libboost-system-dev
      - libboost-thread-dev
      # required packages
      - valgrind
    
    override-build: |
      # don't care: --server-js=off
      # Use system tcmalloc as it's more 'trusted' and would be updated by kernel/security team.
      SCONSFLAGS="--use-system-tcmalloc --disable-warnings-as-errors --use-system-pcre --use-system-snappy --use-system-boost --use-system-zlib --use-system-valgrind --use-system-stemmer --use-system-yaml --ssl"
      arch=$(uname -m)
      if [ $arch = "aarch64" ]; then
          ccflags_arg="CCFLAGS=-march=armv8-a+crc"
      
      else
          ccflags_arg=""
      fi

      if [ $arch = "s390x" ]; then
          SCONSFLAGS="$SCONSFLAGS --allocator=system"
      else
          SCONSFLAGS="$SCONSFLAGS --allocator=tcmalloc"
      fi
      export SCONSFLAGS
      export DESTDIR=$SNAPCRAFT_PART_INSTALL

      scons $ccflags_arg
      scons install $ccflags_arg

      # Strip binaries down to a usable size.
      for file in $SNAPCRAFT_PART_BUILD/build/install/bin/mongo*;
          do strip -s $file;
      done
      mv $SNAPCRAFT_PART_BUILD/build/install/bin $SNAPCRAFT_PART_INSTALL/
