#!/bin/bash

# Create default dirs used in the default args file.
mkdir ${SNAP_COMMON}/db
mkdir ${SNAP_COMMON}/logs
touch ${SNAP_COMMON}/logs/mongo.log

# Don't autostart the daemon
snapctl stop --disable juju-db
